version: '3'

services:
  src:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ["./src:/opt/src"]
    environment:
      PORT: "3000"
      FLASK_DEBUG: "true"
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    ports:
      - "3000:3000"